apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-postgres-probe
  labels:
    {{- include "artifactory-postgres.labels" . | nindent 4 }}
data:
  is-ready.sh: |-
    #!/bin/bash

    set -eou

    user=`grep -m 1 . ${POSTGRES_USER_FILE}`
    database=`grep -m 1 . ${POSTGRES_DB_FILE}`

    psql -U "${user}" -d "${database}" -c "SELECT 1" --tuples-only

